DROP TABLE TB_TEST;
DROP SEQUENCE SEQ;


CREATE SEQUENCE SEQ;

CREATE TABLE TB_TEST(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(100) NOT NULL,
	PW VARCHAR2(100) NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	NICKNAME VARCHAR2(100)
);

INSERT INTO TB_TEST VALUES(SEQ.NEXTVAL, 'ADMIN', '1234','테스트', 'TEST1');
INSERT INTO TB_TEST VALUES(SEQ.NEXTVAL, 'TEST', 'TEST', '테스트2', '♡♡♡♡');
SELECT * FROM TB_TEST ORDER BY SEQ DESC;

